# To be built
LOCAL_UTEST_TARGET    = utest
LOCAL_TARGET    =
LOCAL_SOTARGET  = 
LOCAL_OBJS      = utest.o strutils.o

# Control.
LOCAL_LIBS      = -lutils \
	          -lboost_log -lboost_iostreams \
	          -lboost_program_options \
	          -lgtest \
	          -lpthread -ldl

LOCAL_LIBPATH   = -L$(TCS_LIBDIR)
LOCAL_INCPATH   = 
LOCAL_DEFINES   = 
LOCAL_CXXFLAGS  =
LOCAL_CPPFLAGS  =
LOCAL_LDFLAGS   =
LOCAL_LDSOFLAGS =

include $(ENV_ROOT)/makerules/build.rules
