# To be built
LOCAL_TARGET    = 
LOCAL_SOTARGET  = $(TCS_LIBDIR)/libmiscutils.so
LOCAL_OBJS      = 

# Control.
LOCAL_LIBS      = 
LOCAL_LIBPATH   = 
LOCAL_INCPATH   = 
LOCAL_DEFINES   = 
LOCAL_CXXFLAGS  =
LOCAL_CPPFLAGS  =
LOCAL_LDFLAGS   =
LOCAL_LDSOFLAGS =

include $(ENV_ROOT)/makerules/build.rules
